# Generated by Django 5.1.4 on 2025-01-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Price', models.FloatField()),
                ('Description', models.TextField()),
                ('Category', models.CharField(max_length=255)),
                ('Image', models.URLField()),
                ('Sold', models.BooleanField()),
                ('IsSale', models.BooleanField()),
                ('DateOfSale', models.DateField(null=True)),
            ],
        ),
    ]
